In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing   

# Try to find value for W and b to compute y_data = x_data * W + b  

# Define dimensions
d = 2    # Size of the parameter space
N = 50 # Number of data sample

# Model parameters
W = tf.Variable(tf.zeros([d, 1], tf.float32), name="weights")
b = tf.Variable(tf.zeros([1], tf.float32), name="biases")

# Model input and output
x = tf.placeholder(tf.float32, shape=[None, d])
y = tf.placeholder(tf.float32, shape=[None, 1])

# hypothesis
linear_regression_model = tf.add(tf.matmul(x, W), b)
# cost/loss function
loss = tf.reduce_mean(tf.square(linear_regression_model - y)) / (2*N)

# optimizer
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.00015)
train = optimizer.minimize(loss)

training_filename = "dataForTraining.txt"
testing_filename = "dataForTesting.txt"
training_dataset = np.loadtxt("dataForTraining.txt")
testing_dataset = np.loadtxt("dataForTesting.txt")

# min_max_scaler = preprocessing.MinMaxScaler()  
# training_dataset = min_max_scaler.fit_transform(training_dataset) 
# testing_dataset = min_max_scaler.fit_transform(testing_dataset) 
# print(training_dataset)
# print(testing_dataset)

x_train = np.array(training_dataset[:,:2])
y_train = np.array(training_dataset[:,2:3])
x_test = np.array(testing_dataset[:,:2])
y_test = np.array(testing_dataset[:,2:3])
print(x_train.shape)
print(y_train.shape)


save_step_loss = {"step":[],"train_loss":[],"test_loss":[]}# 保存step和loss用于可视化操作

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)  # reset values to wrong
    steps = 1500000
    for i in range(steps):
        sess.run(train, {x: x_train, y: y_train})
        if i % 100000 == 0:
            # evaluate training accuracy
            print("iteration times: %s" % i)
            curr_W, curr_b, curr_train_loss = sess.run([W, b, loss], {x: x_train, y: y_train})
            print("W: %s \nb: %s \nTrain Loss: %s" % (curr_W, curr_b, curr_train_loss))
            # Accuracy computation
            curr_test_loss = sess.run(loss,{x:x_test,y:y_test})
            print("Test Loss: %s\n" % curr_test_loss)
            save_step_loss["step"].append(i)
            save_step_loss["train_loss"].append(curr_train_loss)
            save_step_loss["test_loss"].append(curr_test_loss)

#画图损失函数变化曲线
plt.plot(save_step_loss["step"],save_step_loss["train_loss"],label='Training Loss')
plt.plot(save_step_loss["step"],save_step_loss["test_loss"],label='Testing Loss')
plt.xlabel('Iteration times')
plt.ylabel('Loss (in billion RMB)')
plt.legend()
plt.show()
#画图损失函数变化曲线
plt.plot(save_step_loss["step"][1:],save_step_loss["train_loss"][1:],label='Training Loss')
plt.plot(save_step_loss["step"][1:],save_step_loss["test_loss"][1:],label='Testing Loss')
plt.xlabel('Iteration times')
plt.ylabel('Loss (in billion RMB)')
plt.legend()
plt.show()

Instructions for updating:
Colocations handled automatically by placer.
[[0.40816327 0.11570248 0.66037892]
 [0.60204082 0.16528926 0.7557215 ]
 [0.55102041 0.30578512 0.57538222]
 [0.63265306 0.20661157 0.73689364]
 [0.37755102 0.07438017 0.67920678]
 [0.51020408 0.         0.85490987]
 [0.24489796 0.05123967 0.59958947]
 [0.15306122 0.24958678 0.31816251]
 [0.17346939 0.37190083 0.21236787]
 [0.31632653 0.19834711 0.49856078]
 [0.23469388 0.48016529 0.1482399 ]
 [0.63265306 0.65289256 0.27556389]
 [0.82653061 1.         0.0727751 ]
 [0.36734694 0.58677686 0.13684409]
 [0.14285714 0.4338843  0.12435117]
 [0.28571429 0.49586777 0.16710315]
 [1.         0.75206612 0.46446772]
 [0.39795918 0.18181818 0.57880332]
 [0.41836735 0.50413223 0.26681059]
 [0.51020408 0.41487603 0.42604521]
 [0.74489796 0.66942149 0.35073377]
 [0.15306122 0.20495868 0.36430021]
 [0.2755102  0.25950413 0.40819649]
 [0.28571429 0.25785124 0.41551057]
 [0.07142857 0.19752066 0.31298367]
 [0.04081633 0.04132231 0.44