# Homework 2: Multivariate Linear Regression

In [1]:
import tensorflow as tf
import numpy as np

## 变量

In [2]:
# Try to find value for W and b to compute y_data = x_data * W + b  

# Model parameters
W = tf.Variable(tf.zeros([2, 1], tf.float32), name="weights")
b = tf.Variable(tf.zeros([1], tf.float32), name="biases")

# Model input and output
x = tf.placeholder(tf.float32, shape=[None, 2])
y = tf.placeholder(tf.float32, shape=[None, 1])

Instructions for updating:
Colocations handled automatically by placer.


## Multivariate Linear Regression Model

In [10]:
linear_regression_model = tf.add(tf.matmul(x, W), b)

# cost/loss function
loss = tf.reduce_mean(tf.square(linear_regression_model - y)) / 100

## Minimize cost with Gradient Descent

In [11]:
# optimizer
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.00015)
train = optimizer.minimize(loss)

## Load the training data

In [12]:
training_filename = "dataForTraining.txt"
testing_filename = "dataForTesting.txt"
training_dataset = np.loadtxt("dataForTraining.txt")
testing_dataset = np.loadtxt("dataForTesting.txt")
x_train = np.array(training_dataset[:,:2])
y_train = np.array(training_dataset[:,2:3])
x_test = np.array(testing_dataset[:,:2])
y_test = np.array(testing_dataset[:,2:3])
print(x_train.shape)
print(y_train.shape)
print(x_train[0:10,])
print(y_train[0:10,])
print(x_test[0:10,])
print(y_test[0:10,])

(50, 2)
(50, 1)
[[101.     1.7 ]
 [120.     2.3 ]
 [115.     4.  ]
 [123.     2.8 ]
 [ 98.     1.2 ]
 [111.     0.3 ]
 [ 85.     0.92]
 [ 76.     3.32]
 [ 78.     4.8 ]
 [ 92.     2.7 ]]
[[641.48]
 [722.3 ]
 [569.43]
 [706.34]
 [657.44]
 [806.38]
 [589.95]
 [351.39]
 [261.71]
 [504.31]]
[[ 93.     0.78]
 [104.     3.82]
 [110.     4.27]
 [ 69.     5.2 ]
 [ 80.     1.22]
 [ 79.     0.87]
 [128.     5.54]
 [107.     4.51]
 [ 75.     3.2 ]
 [ 96.     1.55]]
[[637.07]
 [494.08]
 [502.26]
 [166.46]
 [521.05]
 [539.17]
 [530.48]
 [465.21]
 [347.3 ]
 [602.54]]


## Fit the line

In [14]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)  # reset values to wrong
    steps = 15000
    for i in range(steps):
        sess.run(train, {x: x_train, y: y_train})
        if i % 1000 == 0:
            # evaluate training accuracy
            curr_W, curr_b, curr_loss = sess.run([W, b, loss], {x: x_train, y: y_train})
            print("W: %s b: %s loss: %s" % (curr_W, curr_b, curr_loss))
    print(loss,{x:x_test,y:y_test}))

W: [[0.12614042]
 [0.00496565]] b: [0.00120336] loss: 1859.3881
W: [[ 3.9245932]
 [-1.1602219]] b: [0.06563281] loss: 326.61017
W: [[ 3.9909875]
 [-2.4878497]] b: [0.09503578] loss: 314.82413
W: [[ 4.0561576]
 [-3.79103  ]] b: [0.12414491] loss: 303.46805
W: [[ 4.1201205]
 [-5.070212 ]] b: [0.15296562] loss: 292.52628
W: [[ 4.182912]
 [-6.325843]] b: [0.18150261] loss: 281.9836
W: [[ 4.244535]
 [-7.558352]] b: [0.20976155] loss: 271.8255
W: [[ 4.3050346]
 [-8.768167 ]] b: [0.23774727] loss: 262.038
W: [[ 4.3644056]
 [-9.955708 ]] b: [0.26546454] loss: 252.6075
W: [[  4.4226813]
 [-11.121376 ]] b: [0.29291856] loss: 243.52101
W: [[  4.479887]
 [-12.265585]] b: [0.32011443] loss: 234.76599
W: [[  4.5360417]
 [-13.388723 ]] b: [0.34705633] loss: 226.33035
W: [[  4.5911517]
 [-14.491183 ]] b: [0.3737494] loss: 218.20238
W: [[  4.6452456]
 [-15.57334  ]] b: [0.40019736] loss: 210.37091
W: [[  4.6983414]
 [-16.635578 ]] b: [0.4264054] loss: 202.82509


## 测试模型